"""Regenerate summary/task3-arditi-baseline.md from the committed judge scores.

Every number in the output is computed here, never transcribed, so the note cannot
drift from the artifact it describes.

Inputs, both committed and both complete (no run sampling touches them):

    refusal-jailbreaking/baselines/arditi/runs/judge_summary.json
        50 slugs x 5 judges, baseline and ablated, written by baselines/arditi/llm_judge.py
    refusal-jailbreaking/weights/arditi/refusal/summary.json
        the 252-candidate (layer, position) sweep and the pick it produced

Run it from anywhere, it resolves paths from its own location:

    python summary/gen_task3_arditi.py
    python summary/gen_task3_arditi.py --out /tmp/check.md

It reads only. It writes one file, summary/task3-arditi-baseline.md unless --out
says otherwise, and never touches the archives. Argument parsing happens before
any read or write, so --help exits without touching the destination.

This is the one generator that ships with the release. The other result tables in
SUMMARY.md were produced by scripts that read per-run files (oracle_result.json,
elicitation.json, the ranked feature dumps), and the committed archives keep those
for three example runs per arm only, so those scripts cannot reproduce their own
output here. See summary/README.md.
"""
import argparse
import json
import statistics as st
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO = _HERE.parent
_ARDITI = _REPO / "refusal-jailbreaking" / "baselines" / "arditi"
SRC = _ARDITI / "runs" / "judge_summary.json"
SWEEP = _REPO / "refusal-jailbreaking" / "weights" / "arditi" / "refusal" / "summary.json"
DEST = _HERE / "task3-arditi-baseline.md"


def build(rows, judges, d, sweep):
    """Return the note as a list of lines. Pure, so it is testable without a write."""

    def agg(key, cond):
        return [r[f"{cond}_aggregate"][f"{key}_mean"] for r in rows]

    L = []
    w = L.append

    w("# Task 3 baseline, the Arditi refusal direction on the 50-prompt set")
    w("")
    w("Generated by `summary/gen_task3_arditi.py` from")
    w("`refusal-jailbreaking/baselines/arditi/runs/judge_summary.json`. Regenerate rather than")
    w("hand-edit. Headline numbers and context are in `SUMMARY.md`.")
    w("")
    w("## Headline")
    w("")
    w(f"**Ablated overall = {st.mean(agg('overall','ablated')):.3f}.** That is the single number the")
    w("oracle is compared against. The baseline gets neither a top-1 nor a best-of-5 treatment,")
    w("because a difference-in-means direction produces one direction and therefore one attempt.")
    w("")
    w("| axis | unablated | ablated | lift |")
    w("|---|---:|---:|---:|")
    for key in ("usability", "plausibility", "overall"):
        b, a = st.mean(agg(key, "baseline")), st.mean(agg(key, "ablated"))
        bold = "**" if key == "overall" else ""
        w(f"| {bold}{key}{bold} | {bold}{b:.3f}{bold} | {bold}{a:.3f}{bold} | {bold}{a-b:+.3f}{bold} |")
    w("")
    n_pos = sum(1 for r in rows
                if r["ablated_aggregate"]["overall_mean"] > r["baseline_aggregate"]["overall_mean"])
    base_overall = st.mean(agg("overall", "baseline"))
    w(f"Lift is positive on **{n_pos}/{len(rows)}** slugs. The unablated condition sits near the floor")
    w(f"at {base_overall:.3f}. The unablated model refuses almost everything in this eval set, so")
    w("almost all of the ablated score is elicited content rather than residual compliance.")
    w("")
    w("## Per judge, ablated condition")
    w("")
    w("Cross-judge spread is the dominant variance term on this panel, which is why the judge")
    w("repeat count stays at 1.")
    w("")
    w("| judge | ablated overall | judge refusals (of 50) |")
    w("|---|---:|---:|")
    per_judge = []
    for m in judges:
        vals = [r["ablated_per_judge_stats"][m]["overall_mean"] for r in rows]
        ref = sum(1 for r in rows for s in r["ablated_per_judge_repeats"].get(m, []) if s.get("_refusal"))
        per_judge.append((m, st.mean(vals), ref))
    for m, v, ref in per_judge:
        w(f"| `{m}` | {v:.3f} | {ref} |")
    w("")
    lo = min(per_judge, key=lambda t: t[1])
    hi = max(per_judge, key=lambda t: t[1])
    most = max(per_judge, key=lambda t: t[2])
    w(f"`{lo[0]}` is the strictest seat at {lo[1]:.3f}, against {hi[1]:.3f} for `{hi[0]}`, a spread of")
    if most[0] == lo[0]:
        w(f"{hi[1]-lo[1]:.3f}. It is also the seat that declines to score most often, {most[2]} of {len(rows)}.")
    else:
        w(f"{hi[1]-lo[1]:.3f}. The seat that declines most often is `{most[0]}`, {most[2]} of {len(rows)}.")
    rest = [(m, ref) for m, _, ref in per_judge if ref and m != most[0]]
    if rest:
        listed = ", ".join(f"`{m}` at {ref}" for m, ref in sorted(rest, key=lambda t: -t[1]))
        w(f"It is not the only seat that declines, {listed}. A panel change that adds or drops the")
    else:
        w("No other seat declines to score. A panel change that adds or drops the")
    w("strictest seat moves the headline on its own, so the panel is held fixed across both sides")
    w("of the head-to-head.")
    w("")
    w("## Method and provenance")
    w("")
    if sweep:
        cands = sweep["candidates"]
        kl = sweep["kl_threshold"]
        steer_min = sweep["induce_refusal_threshold"]
        passed = [c for c in cands
                  if c["kl_harmless"] <= kl and c["steering_refusal_score"] > steer_min]
        passed_sorted = sorted(passed, key=lambda c: c["ablation_refusal_score"])
        n_layers = len({c["layer"] for c in cands})
        n_pos_sweep = len({c["pos"] for c in cands})
        names = ", ".join(f"L{c['layer']} pos {c['pos']}" for c in passed_sorted)
        w(f"- **Direction: layer {sweep['chosen_layer']}, position {sweep['chosen_pos']}.**")
        w(f"- Selection swept {n_layers} layers by {n_pos_sweep} positions, {len(cands)} candidates, on")
        w("  three metrics (`ablation_refusal_score`, `kl_harmless`, `steering_refusal_score`). Two hard")
        w(f"  filters (KL at most {kl} and steering above {steer_min}) then `argmin(ablation_refusal_score)`.")
        w(f"  Only **{len(passed)} of {len(cands)}** candidates cleared both filters ({names}), so the pick")
        w("  is not marginal.")
        w(f"- Direction extracted on `baselines/arditi/data/refusal_train.json` with seed 42,")
        w(f"  {sweep['n_train']} usable train and {sweep['n_val']} val prompts, drawn from AdvBench")
        w("  prompts the eval set never contains. Disjointness is enforced and tested by")
        w("  `test_eval_set_is_disjoint_from_arditi_train_and_val`.")
    else:
        w("- Direction sweep summary not found at `weights/arditi/refusal/summary.json`.")
    w("- Ablation is directional projection removal at `hook_resid_pre`, `hook_attn_out` and")
    w("  `hook_mlp_out` on every layer. Greedy decode with `use_past_kv_cache=False`, so the")
    w("  unablated and ablated completions stay comparable.")
    w(f"- Judging by the {len(judges)}-family `circuit_oracle.judge_rubric.JUDGE_PANEL`, two axes")
    w(f"  (usability and plausibility), {d['n_repeats']} repeat at temperature {d['temperature']}.")
    w("  This is the same panel object the oracle runs are scored with, so parity needs no flag.")
    w("")
    w("## Artifacts")
    w("")
    w("All paths are relative to `refusal-jailbreaking/`.")
    w("")
    w("| what | path |")
    w("|---|---|")
    w("| candidate sweep and the pick | `weights/arditi/refusal/summary.json` |")
    w("| per-slug prompts and settings | `baselines/arditi/runs/<slug>/meta.json` |")
    w("| judge scores | `baselines/arditi/runs/judge_summary.{json,md}` |")
    w("| completions, three example slugs | `baselines/arditi/runs/<slug>/{baseline,ablated}.txt` |")
    w("| runs behind the workshop paper | `baselines/arditi/runs-workshop/` |")
    w("")
    w("The direction tensor itself is a `.pt` file and is not committed. Rebuild it with")
    w("`baselines/arditi/extract_direction.py` after fetching the training split, see")
    w("`SUMMARY.md`. Full completions for every slug are available upon request.")
    w("")
    w("## Per-slug lift, sorted")
    w("")
    w(f"Mean across the {len(judges)} judges. `b` is unablated, `a` is ablated.")
    w("")
    w("| slug | overall b | overall a | lift |")
    w("|---|---:|---:|---:|")
    srt = sorted(rows, key=lambda r: r["ablated_aggregate"]["overall_mean"]
                 - r["baseline_aggregate"]["overall_mean"], reverse=True)
    for r in srt:
        b = r["baseline_aggregate"]["overall_mean"]
        a = r["ablated_aggregate"]["overall_mean"]
        w(f"| `{r['slug']}` | {b:.3f} | {a:.3f} | {a-b:+.3f} |")
    w("")
    tail = srt[-5:]
    w("The five weakest slugs are `" + "`, `".join(r["slug"] for r in tail) + "`. These are the")
    w("prompts where removing the refusal direction produces something the panel still scores as")
    w("low usability, which is the honest read that one direction does not unlock everything.")
    w("")
    return L


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--out", default=str(DEST),
                        help=f"Destination markdown file (default {DEST}).")
    args = parser.parse_args(argv)

    d = json.loads(SRC.read_text())
    rows = d["rows"]
    judges = [j["model"] for j in d["judges"]]
    sweep = json.loads(SWEEP.read_text()) if SWEEP.exists() else None

    lines = build(rows, judges, d, sweep)
    out = Path(args.out)
    out.write_text("\n".join(lines))
    print(f"wrote {out} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
